version: '3.8'

services:
    dev:
        image: fastify-mongoose-plugin-dev
        build: 
            context: ../
            dockerfile: docker/dev/Dockerfile
            args:
                - IDIR=fastify-mongoose-plugin
                #- BMODE=production # default development on Dockerfile
        volumes:
            - ../:/ws/fastify-mongoose-plugin:cached
            # node_modules in un volume temporaneo che non mi sovraccarica il prj reale in debug
            - dev-modules:/ws/fastify-mongoose-plugin/node_modules 
            - pnpm-store:/home/node/pnpm/store
        depends_on:
            db:
                condition: service_healthy

    # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        deploy:
            resources:
                limits:
                    cpus: 2
    db:
        image: mongo:4.4.18
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: test
        deploy:
            resources:
                limits:
                    cpus: 2
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 3s
            retries: 5
volumes:
    dev-modules:
    pnpm-store:

networks:
    default:
        name: docker_default
        external: true
